spring:
  cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          service-name: ${spring.application.name}
          instance-id: ${spring.application.name}:1
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics