spring:
  cloud:
      consul:
        discovery:
          service-name: ${spring.application.name}
          instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics